### ISSUE TITLE
[Improvement] Scroll workspaces using scrollwheel when pointer on top of indicator.

### ISSUE THREAD

**Issue by 0Raik** [Favo02/workspaces-by-open-apps#18]
Yeah, basically the basic [**Workspace Indicator**](https://extensions.gnome.org/extension/21/workspace-indicator/) from gnome can do this. Alternatively anyone can use [**Top Panel Workspace Scroll**](https://extensions.gnome.org/extension/701/top-panel-workspace-scroll/) to do this across the entire topbar. I can't because I use that action to scroll volume with [**Volume Scroller**](https://extensions.gnome.org/extension/5904/volume-scroller/).

Thanks for your time dveloping this extension. Cheers!

**Comment by Favo02** [comment]
Thanks for the idea!

Added in v6 (#20), waiting for approval on the GNOME extensions store, should be out soon.
