### ISSUE TITLE
[Improvement] Monochrome Icons option

### ISSUE THREAD

**Issue by 0Raik** [Favo02/workspaces-by-open-apps#19]
Monochrome 

![il_570xN 2685499598_nshm](https://github.com/Favo02/workspaces-by-open-apps/assets/5239948/d5b02864-98db-41fc-946c-1e0899704119)

Is da best!

![Screenshot from 2023-05-17 00-04-12](https://github.com/Favo02/workspaces-by-open-apps/assets/5239948/993d34d3-8de5-41aa-9794-1bcc9ea193c0)

Look at it @_@

**Comment by Favo02** [comment]
You are right, these icons just looks off, monochrome is needed.

Added in v6 (#21), already published on the GNOME extensions store.
