### ISSUE TITLE
Ability to change workspace index number to custom workspace names

### ISSUE THREAD

**Issue by bfapps** [Favo02/workspaces-by-open-apps#24]
It would be great if you could add the feature which allows us to name different workspaces as we wish. For example: Space 1, Space 2, Space 3. 
Many thanks in advance.

**Comment by Favo02** [comment]
Thank you for your feedback! Adding this to TODO list.

**Comment by Favo02** [comment]
Sorry for the delay, but finally this is ready.

Added in v7 (#27), already published on the GNOME extensions store.

_To correctly visualize the name of a workspace after the renaming switch to another workspace to trigger a refresh (working on a fix #26)_
