### ISSUE TITLE
Touch support

### ISSUE THREAD

**Issue by Kuchenmampfer** [Favo02/workspaces-by-open-apps#28]
Hi,
I recently discovered this amazing extension on my tablet, thank you for making it.
There is one reason I currently combine it with another workspace indicator extension though: clicking with my finger on a workspace/application does not work. I can click with my pen and mouse, but they are not always conveniently at hand. So I'd love to see this getting support.

**Comment by Favo02** [comment]
Thanks for your feedback!

I have a touch display myself but never tried to use the extension with my fingers. (Almost) every other extension I have installed works, I will dig a bit and find how to add touch support ASAP.

**Comment by Kuchenmampfer** [comment]
That would be great, thank you <3

**Comment by Favo02** [comment]
Touch support added in #33.

New version will be out soon.
