### ISSUE TITLE
Feature Request: add support for previous versions of Gnome-shell

### ISSUE THREAD

**Issue by maxborn** [Favo02/workspaces-by-open-apps#29]
Hi, I discovered this extension recently, and it's the best virtual desktop manager I've ever seen. I'm using it on some of my computers already, however, some of my older installs use Gnome-shell versions as old as 40. I was wondering, then: would it be possible to add support for older Gnome-shell versions (ideally as far back as 40)? If it's not too much trouble I mean. I thank you in advance for taking the time to think about this. And thank you for such a useful extension. Regards, Max.

**Comment by Favo02** [comment]
Thanks for your feedback!

I will need some tests on older versions to check if anything breaks. I will update this issue as soon as possible.

**Comment by maxborn** [comment]
I did a quick test on Gnome 40, by replacing the original line with this one in metadata.json:
  "shell-version": ["40", "41", "42", "43", "44" ]
It seems to be working fine. I guess that if it works for v40 and v44, it should work for everything in between.
I hope this helps, and thanks again.

**Comment by Favo02** [comment]
Thanks for testing out version 40!
I added the metadata necessary to make the extension work on shell 40, 41, 42, 43 and 44 (in #32).

I am planning a few more fixes for the new of the extension, so the fix is not out yet, I will let you know when the extension is upgradable.

**Comment by Favo02** [comment]
New version (v8) is under review, should be out in a few hours.
