### ISSUE TITLE
Feature Request: Limit Maximum Widget Width (otherwise it might eat up half the taskbar or more)

### ISSUE THREAD

**Issue by maxborn** [Favo02/workspaces-by-open-apps#35]
Hi,
thanks again for this very useful extension. I've been using it and it's a life changer. I have a few comments on potential improvements though. For now, the biggest problem I'm facing is that the visualization on the taskbar (I'm using Dash to Pannel), can get really big (wide) and eat a lot of taskbar space, depending on the number of desktops and open windows.

I know changing the behavior of the extension radically might not be easy, but just in case there is something you could improve, here are a few ideas to make it easier to deal with a big number of desktops or windows. It will be very convenient to have options to set one or more of these behaviors:
1. Limit the horizontal size the visualization can use, and use scroll bars (maybe one per desktop, or a single one for everything).
2. Group similar windows (say Firefox windows) into a single icon, like taskbars can typically do with taskbar buttons.
3. Make the widget a small preview (maybe showing the number of desktops, but no app details yet), then when clicked a full menu could be shown, as a pop-up, like a start menu of sorts (think arcMenu). The desktops could be each on a row, displaying the list of apps like the widget does now, and stacked on top of each other). This will resemble a window-list more than a desktop switcher, but it can get the same job done, with one more click, and without eating so much taskbar space sometimes.
4. Create a separate panel for the desktop switcher, something that can be, say hidden on the side of the screen and displayed when the mouse hovers nearby.
In any case, the widget is very useful, and I use it most of the time. Only when I'm working on projects with too many windows (say, dozens of Python plot screens) that I temporarily switch to a more traditional desktop management widget (like workspace indicator).
Thanks for taking the time to look into this.
Cheers.
Max.

**Comment by Favo02** [comment]
First of all thank you!

All of these are great ideas, but pretty complex. I will do my best to implement into the extension the most features possible. More customization is better than less customization.

_It will take some time._

**Comment by Favo02** [comment]
I added a few settings in version 9 (release #46) that should help you: group same application (2.) and icons limit (1.).\
_The new version should be out on gnome extensions store by tomorrow._

The preview (3.) is really hard to achieve due to the nature of the application, this is not a dock but just some buttons in the panel, so I gave up, you will not have a preview any time soon :(.\
Same thing for the desktop switcher on mouse click or hover (3.), it is pretty complicated to realize and I think it is not worth it, sorry :(.

I hope new settings are useful and simplify your job!

**Comment by maxborn** [comment]
Hi Luca, that's awesome! I'll give it a try as soon as it's out.
I wasn't expecting so much improvement, honestly.
Congratulations and thanks again for creating and maintaining this wonderful extension.
Cheers.
Max.
