### ISSUE TITLE
remove 'ALL' text when using with desktop icons ng

### ISSUE THREAD

**Issue by cpu012** [Favo02/workspaces-by-open-apps#36]
on the top left there is an 'ALL' label that goes away when I disable the desktop icons ng (DING) extension. turning off this extension removes all the icons including the 'ALL' text.

![image](https://github.com/Favo02/workspaces-by-open-apps/assets/58913437/968c60a4-cd99-47e8-9fa5-b03b2cb2e5e9)

**Comment by Favo02** [comment]
Thanks for the feedback. I try to find a solution as soon as possible, I will keep you updated.

**Comment by cpu012** [comment]
This also happens with conky, and it leaves conky icons which cannot be clicked

**Comment by cpu012** [comment]
maybe adding an option for programs that should be excluded by this extension might solve the problem

**Comment by Favo02** [comment]
Adding an "Excluded apps" setting is exactly what I was thinking for, I just didn't have any spare time to code this.

With GNOME 45 I will be forced to do some refactor, so I will soon implement this, sorry for the delay!

**Comment by Favo02** [comment]
Added in version 9 (release #46) a setting to ignore some application. Instructions on how to ignore an application are listed in release #46 and in extension settings.

_The new version should be out on gnome extension store by tomorrow._
