### ISSUE TITLE
Maybe Bug? Ghost App icons in the ALL section

### ISSUE THREAD

**Issue by Ivaylo-Korakov** [Favo02/workspaces-by-open-apps#38]
Hi,

Thank you so much for making such a wonderful extension!
I wanted to ask and maybe report a bug where you have in my case 2 ghost app icons in the all section. I have renamed mine to just A. 
Here is a screenshot:
![image](https://github.com/Favo02/workspaces-by-open-apps/assets/14264329/f21cf1b4-e440-43ad-a725-2dfc9bf0ca79)
I can confirm I don't have any windows that are invisible from some other applications (this is a new install)

The behavior of those icons is a bit weird:
If you have a window selected when you click the icons nothing happens (then don't get selected)
If you are on an empty workspace and you have no window selected then you can click the icons and switch between them but nothing actually happens. No windows pop up etc,
![image](https://github.com/Favo02/workspaces-by-open-apps/assets/14264329/204555f8-607c-46d5-b1d0-d10ad737aef2)
![image](https://github.com/Favo02/workspaces-by-open-apps/assets/14264329/58b3b4ba-efd9-4504-b123-c1d6c96d1df0)

And again thank you for making this :)

**Comment by Favo02** [comment]
Thanks for the feedback!

I will try to find a fix for this bug, a few more details could be really useful:
do you have installed an extension to add icons to desktop (on a distro where desktop icons are not stock, like fedora)?

**Comment by Ivaylo-Korakov** [comment]
I am using Pop OS and yes the icons don't seem to be the standard ones that come with Gnome.

Here are some general system details:
![image](https://github.com/Favo02/workspaces-by-open-apps/assets/14264329/9120bd48-2ebb-4622-9f1a-3c6dfc551156)

Here are the extensions I have:
![image](https://github.com/Favo02/workspaces-by-open-apps/assets/14264329/757a12ad-2fbe-400d-9944-292cc2363d15)

**Comment by Favo02** [comment]
Thanks again for these info, I will try to find out whats causing the problem.

**Comment by Favo02** [comment]
Added in version 9 (release #46) a setting to ignore some application. Ignoring the app that renders in "A" indicator should solve the issue.

Instructions on how to ignore an application are listed in release #46 and in extension settings.

_The new version should be out on gnome extension store by tomorrow._
