### ISSUE TITLE
Porting to GNOME 45

### ISSUE THREAD

**Issue by antrmn** [Favo02/workspaces-by-open-apps#39]
GNOME broke (once again) the inertia on its product and requires all extensions to comply with the new import system: https://blogs.gnome.org/shell-dev/2023/09/02/extensions-in-gnome-45/

**Comment by Favo02** [comment]
Thanks for opening the issue!
I will port the extension to the GNOME 45 as soon as possible (the new update will break old versions, but I think an old version of the extension will still be available on the extension store).

**Comment by khalangy** [comment]
I just updated to gnome 45 and extension not working :( 
I tryed to follow the indications to port the extension but I'm not a developper :sweat_smile: , so I wait for your port :smile_cat: 
Thanks

**Comment by Favo02** [comment]
@khalangy GNOME 45 broke backwards compatibility, so I need to port the extension manually tweaking some things.
It sucks but I don't have a lot of time, I hope to do that before next week.

Thanks for the understanding :)

**Comment by Favo02** [comment]
Last update for GNOME <45 just released. I will start working on GNOME 45 version starting tomorrow.

**Comment by revo09** [comment]
I have quickly tweaked the changes for GNOME 45, locally on my machine. It's mostly about imports, transitioning the prefs to a class and disabling the native workspaces control when this extension is enabled (could also add a toggle in the settings).

**Comment by Favo02** [comment]
I send for review version 10 (#48) of the extension, which supports GNOME 45. Waiting for approval.

**Comment by Favo02** [comment]
New version available on [GNOME extensions store](https://extensions.gnome.org/extension/5967/workspaces-indicator-by-open-apps/).

Bug #49 could affect also this version, I already send for review a fixed version also for GNOME 45.
