### ISSUE TITLE
Dialogs, popovers and tooltip seen make additional icons appear

### ISSUE THREAD

**Issue by antrmn** [Favo02/workspaces-by-open-apps#40]
Steps to reproduce:

1. Start the extension
2. Open `Settings` on GNOME
3. Open the hamburger menu, on the upper right corner
4. A popover appears and you can see two "Settings" icons in the panel instead of just one

Same procedure for any other app with a popover menu. I also encountered the same issue with Firefox's right click context menu and the tooltip box when the cursor is hovering on tabs

**Comment by Favo02** [comment]
Thanks for the feedback.

I have a fix in mind for this problem I encountered myself. I will update soon.

**Comment by Favo02** [comment]
Released a fix to mitigate _(I cannot reproduce the bug anymore)_ this issue in version 9 (release #46), so I will consider this fixed. The new version should be out on gnome extensions store by tomorrow.

Open a new issue if the problem is still there.
