### ISSUE TITLE
[Feature Request] Style for minimized apps

### ISSUE THREAD

**Issue by antrmn** [Favo02/workspaces-by-open-apps#41]
A way to distinguish opened apps from minimized apps would be useful. My idea was to make minimized apps appear slightly more transparent, but that is already reserved for non-focused icons.

**Comment by Favo02** [comment]
Thanks for the feedback!

I use an auto-tiler, so I simply don't have minimized applications, I completely forgot about this. I will add some setting for minimized apps in the next update.

**Comment by Favo02** [comment]
I was thinking about reducing saturation on minimized apps icons. Maybe even completely grayscale.
The alternative is making them smaller.

@antrmn what are your thoughts about that? I am working on a few other things so I will wait for your feedback before pushing an update.

**Comment by antrmn** [comment]
Sorry for the late reply.

I may sound biased since I have configured the extension so that it shows an overline on the focused app. 

Having the choice to unsaturate minimized apps would be great, but having "No tweaks|Set saturation|Set opacity" options for both minimized and unfocused apps would be the most unopinionated choice. 

In my case, I'd set it so that unfocused apps have no overline while minimized apps would have less opacity.

**Comment by Favo02** [comment]
Added in version 9 (release: #46). Should be out on the gnome extensions store by tomorrow.

**Comment by antrmn** [comment]
The notification sneaked out of my eyes.
Thank you very much for the feature!
