### ISSUE TITLE
Ignore applications by regex

### ISSUE THREAD

**Issue by bakedbean** [Favo02/workspaces-by-open-apps#54]
Running Ubuntu 22.

The active workspace always shows a generic window/desktop icon.  When viewing the log, it shows as `window:x` where "x" is an incrementing number that increases each time the system sleeps and wakes up.

Adding it to the ignore list removes it, until the number increments again.  Not sure what is causing it to display in the first place, but would be neat if the ignore list could take a regex like `/window/i`

![image](https://github.com/Favo02/workspaces-by-open-apps/assets/952898/ae70cffc-1c3f-461d-96d8-6b096bb7bf3f)

Minor issue overall and great extension!

**Comment by bakedbean** [comment]
added this to `extension.js` which fixed it for me:
```
if (app.get_id().match(/window/i)) return false;
```
Could probably figure out a way to test for the regex pattern while iterating `icons_ignored`, but I'm not sure this isn't an issue specific to my system.

**Comment by Favo02** [comment]
I think the idea to ignore Apps matching a regex is a great idea, I will implement for sure this in the next update.

Thanks for the feedback and for the idea!

**Comment by bakedbean** [comment]
I got this working locally: 
```
const windows = workspace
      .list_windows()
      // filter out ignored apps
      .filter(win => {
        if (!win) return false
        const app = Shell.WindowTracker.get_default().get_window_app(win)
        if (!app) return false
        // perform case insensitivity regex match on ignored strings
        const matches = this._settings.icons_ignored.filter(i => {
          const regex = new RegExp(i, 'i');
          return regex.test(app.get_id());
        });
        return !this._settings.icons_ignored.includes(app.get_id()) && matches.length < 1
      })
```
It's a bit aggressive and could easily wind up ignoring valid things... happy to toss up a PR but you can probably come up with something better.

**Comment by Favo02** [comment]
Done in #55, release on GNOME extensions store in a few days
