### ISSUE TITLE
CSS issues

### ISSUE THREAD

**Issue by 0Raik** [Favo02/workspaces-by-open-apps#59]
Been a user since day one and loved every improvement along the way, specially when they were my suggestions :smile: but I've had this problem when using both Workspace Indicator and this extension. I think Workspaces by open apps piggy backs on Workspace Indicator as I did some CSS changes to Workspace Indicator to fit a thin panel bar with better colors and this is the result:

![Screenshot from 2023-11-27 18-17-17](https://github.com/Favo02/workspaces-by-open-apps/assets/5239948/82cd1cb0-0fc9-499c-a214-7af784b0dd90)

But when I enable Workspaces by open apps it distorts Workspace Indicator like so:

![Screenshot from 2023-11-27 18-18-41](https://github.com/Favo02/workspaces-by-open-apps/assets/5239948/b7be0711-43c9-412a-aeb4-dbef33858ead)

And I don't know why. I don't think its supposed to happen but I guess the extension is using workspace indicator in a way it interferes.

Lastly we have an option in the extension to enable round indicator borders but the result looks sharp, not round. Not looking nice with the Gnome 'round' aesthetic. Barely better than the default 'square' bars.
I've been trying to make them round but I barely know CSS so here I am.

Thank you so much for the time and effort put in this awesome and useful extension. Hopefully we see more improvements along the way. Have a great day!

**Comment by Favo02** [comment]
Thank you for the feedback and **sorry for the delay**.

I think this could be an issue with _shared_ CSS classes (both extensions use the same name for some classes). I will add some _unique characters_ in each CSS class name (something like `wboa_classname`) to avoid issues like this.

In the meantime (I honestly don't know when the next update will be) you could edit the class names yourself (just replace in whole project the CSS class names) and check if this fixes the problem.

**Comment by 0Raik** [comment]
Don't worry. I also took over a year to report this.

Unfortunatelly I don't know how to fix this even with your explanation so I will wait for the fix. 

Thank you for your time and have a wonderful day!

**Comment by Favo02** [comment]
Fixed in #65, renaming all CSS classes. Release on GNOME extensions store in a few days.
