### ISSUE TITLE
Window not displayed as focused when tooltips are there

### ISSUE THREAD

**Issue by Favo02** [Favo02/workspaces-by-open-apps#61]
When a window tooltip, popover or dialog is rendered, the window is not displayed as focused.

**Comment by ybda** [comment]
Hey. Thank you so much for your wonderful extension. I'm not sure if my issue is related to this. When tooltip appears in nautilus or sometimes in firefox, icon from workspaces disappear. 
Images that show the issue:
https://disk.yandex.ru/d/fUDRBZkYOlbYzQ

**Comment by Favo02** [comment]
Hey @ybda, thanks for the report!

Yes, the problem is related to tooltips / dialogs and popover, which are considered a different application than the "main window".

I will investigate and try to release a feature as soon as possible. I will keep this issue updated.

**Comment by Favo02** [comment]
I made some small improvements to the algorithm that decides to skip a window or render its icon. The changes are available on [ignored-windows-improvements](https://github.com/Favo02/workspaces-by-open-apps/tree/ignored-windows-improvements) branch.

It seems to work on my local machine, but I didn't spent much time testing it, your feedback would be very valuable.

**Comment by ybda** [comment]
@Favo02 Affirmative. I'll check the branch out in the next couple of days. I'm time-constrained at the moment.

**Comment by ybda** [comment]
@Favo02 On [ignored-windows-improvements](https://github.com/Favo02/workspaces-by-open-apps/tree/ignored-windows-improvements) branch I cannot reproduce this issue. Tested in firefox, nautilus, brave browser, webstorm and a couple of others. Good job!
