### ISSUE TITLE
[Feat] Option to disable scrolling

### ISSUE THREAD

**Issue by FelixFourcolor** [Favo02/workspaces-by-open-apps#74]
First, thank you for your work, it is very useful. :slightly_smiling_face:

There are extensions that let you scroll the panel to switch workspace like [panel scroll](https://github.com/sunwxg/gnome-shell-extension-panelScroll) and [Panel Workspace Scroll](https://github.com/PolyMeilex/gnome-shell-extension-panel-workspace-scroll). This extension's scrolling conflicts with them: if both are enabled, you skip 2 workspaces at once.

I suggest adding an option to disable scrolling. If a user is using another panel scroll extension, they could disable scrolling for this extension to avoid conflict.

**Comment by Favo02** [comment]
Thank you for the feedback!

Having an option that disable scroll makes a lot of sense, in fact I even thought that was already there (but it is not).

This should not take long, I will keep this issue updated.

**Comment by Favo02** [comment]
Setting added in #76, will release on [extensions.gnome.org](https://extensions.gnome.org) soon.
