### ISSUE TITLE
[Feature] Invert workspace and current app indicator position

### ISSUE THREAD

**Issue by 0Raik** [Favo02/workspaces-by-open-apps#79]
Hi again :D

Thank you so much for such a useful and now essential extension. Thanks for improving the Gnome experience. Really appreciated. Also for the recent update, I was the one who reported the issue to the *Open Bar* developer. Glad to see things improving so fast.

Currently using custom CSS and got the idea to swap the indicator of current workspace to the top and the current app to the bottom. Unfortunately I can't do it myself as I know jack about JS or programming in general. I can barely do some customization thru editing the CSS files but I know to swap the indicators would only be possible to do it changing the source code which is something beyond me...

Thank you so much for the time and effort put in this useful extension! have a wonderful day and cheers!!

**Comment by Favo02** [comment]
Thanks again for the feedback, a lot of improvement is thanks to you and other users that care about the extension.

I will try to implement a setting to swap app and workspace indicators position. I will keep the issue updated.

**Comment by Favo02** [comment]
A new setting to invert indicator positions has been added in #85, update will be released on Gnome extensions store soon.
