### ISSUE TITLE
Add settings to reorder the position of the indicator 

### ISSUE THREAD

**Issue by 0Raik** [Favo02/workspaces-by-open-apps#8]
-Can't open the settings for the extension so you got your first bug right there.

-Shows up always to the left. Doesn't like to be re-organized by Top Bar Organizer which is the OG extension to order all your topbar extensions. 

Gnome 43.4 
Manjaro

**Comment by Favo02** [comment]
Thanks for the feedback!

Both the problems you described are in the to-do list, I will try to fix as soon as possible.

**Comment by 0Raik** [comment]
Great to hear! Have a wonderful day.

**Comment by Favo02** [comment]
Version 3 is available on gnome extension store (automatic update on login if already installed).

The indicator is still not detected by Top Bar Organizer (I need to do some reverse engineering, not easy to fix), but the new settings for `box` and `index` selection should be a good workaround.

@0Raik Let me know if this update address your issues.

**Comment by 0Raik** [comment]
Trying it just now. You just did an amzing job. Thank you.

Works really well. I guess setting an index for possition is as good as using Top Bar Organizer. 
So far I think works great. It seems the only feature you're missing would be to scroll workspace using the scrollwheel when pointer is on top of the extension just like good old Workspace Indicator. Let me give you 5***** on Gnome extensions webpage.

Have a wonderful day!

**Comment by Favo02** [comment]
Adding the scroll using the scrollwheel to TODO. Thanks again!
