### ISSUE TITLE
Workspace names not centered

### ISSUE THREAD

**Issue by twouters** [Favo02/workspaces-by-open-apps#80]
![image](https://github.com/Favo02/workspaces-by-open-apps/assets/170895/a412bdd8-85cf-472f-8425-9261d5545106)

As you can see in above screenshot, the workspace name (indexes in this case) is not vertically centered (or is the hover background positioning wrong?)

**Comment by Favo02** [comment]
Thanks for the feedback!

Currently, centering text is done "manually" _(add `n` pixels to top margin)_ and it works only if the panel size is not modified _(via other extensions like Just Perfection)_, do you recall if you modified the height of the panel (black top bar)?

Anyway, I am trying to find a better way to center the indicators, I will keep this issue updated

**Comment by twouters** [comment]
I don't remember changing the panel height but i'll look it up. Maybe it's related to the display resolution or wayland vs. x11?

**Comment by twouters** [comment]
> I don't remember changing the panel height but i'll look it up. Maybe it's related to the display resolution or wayland vs. x11?

Couldn't find any setting or extension to change its size, so I guess not.
Tested with few different resolutions and none of those impacted the behavior.

**Comment by Favo02** [comment]
I found a nicer way to center things in #83, the height shouldn't matter now. Please reopen the issue if the problem persists.

The update will be released on gnome extensions store soon.
