### ISSUE TITLE
Hovering app icon changes workspace name positioning

### ISSUE THREAD

**Issue by twouters** [Favo02/workspaces-by-open-apps#81]
[Screencast from 2024-05-02 10-55-59.webm](https://github.com/Favo02/workspaces-by-open-apps/assets/170895/2822e327-a7b6-4df5-a403-356a021d648c)

As you can see from the above screencast (sorry for bad resolution) the workspace name changes position when hovering the app icon.

This only seems to happen when only one application is active on a workspace and not when two or more application icons are displayed.

**Comment by Favo02** [comment]
Thanks again for the feedback!

As I said in issue #80, the centering is done manually, and it looks like broken on some machines (this issue doesn't affect my machine or my friends'), I am trying to find a better way to center things.

**Comment by Favo02** [comment]
This should be fixed in #83, please reopen the issue if the problem persists.

The update will be released on gnome extensions store soon.
