### ISSUE TITLE
After removal of css_inline_workspace I don't see workspace border at all

### ISSUE THREAD

**Issue by ybda** [Favo02/workspaces-by-open-apps#82]
@Favo02 Huge respect for active improvement of one of THE BEST and ESSENTIAL extensions for GNOME.

I stuck a bit. Likely I'm just being stoopid idk.

Expected behavior: border for active workspace is kept and now can be controlled only through stylesheet.css (I don't need to configure workspace bottom border color through anything but css)
Actual behavior: I stop seeing any border at all

In following commit I remove workspace style (`style: css_inline_workspace`) and I expect to see bottom border anyways because css selector `.wboa-workspace.wboa-active` has `border-bottom: 2px solid #99c1f1;`
Commit that causes workspace border to disappear
https://github.com/ybda/workspaces-by-open-apps/commit/66d78359c9258f04eb37131ce02eef8c1d2c1468

Moreover, I made a very similar change but for app icons and it does work just fine, as I expect it 
https://github.com/ybda/workspaces-by-open-apps/commit/489d751c090721498812fa390dc33003787c1f68

Note:
I tried the same change on your repo, not in my fork. The results are the same.

**Comment by Favo02** [comment]
Thanks again!

I am currently heavily refactoring the extension code, right now is pretty bad. I hope to achieve an easier customizability.

Anyway, I will look into this issue as soon as I release the refactored version.

**Comment by Favo02** [comment]
Sorry for the late reply.

Anyway, I am not a big fan of TypeScript, I don't think I will ever port the extension, it is already a pain to write JavaScript code.

Back to the original issue: I completely refactored CSS classes, can you try again and let me know if there are any issues?

**Comment by ybda** [comment]
> Anyway, I am not a big fan of TypeScript, I don't think I will ever port the extension, it is already a pain to write JavaScript code.

Typescript certainly has its painful aspects, I certainly can see your point. Thanks for consideration!

> Back to the original issue: I completely refactored CSS classes, can you try again and let me know if there are any issues?

Issue was resolved. You've done an amazing job with refactoring. This commit does the job as expected - https://github.com/ybda/workspaces-by-open-apps/commit/253c9293f5fa08752ed7f575f0001c3956b3df85

There's a thing that I don't get though. Why `border-bottom: 2px solid white;` does not work (no bottom border at all). But this works just fine:
```
border-bottom: 2px solid;
border-color: white;
```
And I observed no error logs whatsoever (`journalctl /usr/bin/gnome-shell -f -o cat`)

**Comment by Favo02** [comment]
I'm glad you found a solution!

> There's a thing that I don't get though. Why border-bottom: 2px solid white; does not work (no bottom border at all). 

The only idea I have is the [color override at line 218 if extension.js](https://github.com/Favo02/workspaces-by-open-apps/blob/d745c0d42f4bce80ac494c81f82c18cf5d7e0a55/src/extension.js#L218) somehow interferes with `border-bottom`.

**Comment by ybda** [comment]
> The only idea I have is the [color override at line 218 if extension.js](https://github.com/Favo02/workspaces-by-open-apps/blob/d745c0d42f4bce80ac494c81f82c18cf5d7e0a55/src/extension.js#L218) somehow interferes with `border-bottom`.

I get rid of this overriding in mentioned commit https://github.com/ybda/workspaces-by-open-apps/commit/253c9293f5fa08752ed7f575f0001c3956b3df85
So no, that's not it

**Comment by Favo02** [comment]
I have no idea, CSS works in mysterious ways
