### ISSUE TITLE
[FEATURES REQUEST] ADD ICONS STYLING OPTIONS

### ISSUE THREAD

**Issue by JE-Amouel** [Favo02/workspaces-by-open-apps#87]
hi,
i use dash to panel  as my desktop's shell's panel, like most of the time i use my laptop, i have a small screen for my work, so better to keep strict and necessary info only , had hopefully your great extension helped a lot to solve the space problem by merging in a clever way taskbar and active workspace indication, which are generally my main information when it come to check my panel, that great,
but it looks like there is a lake of customization options when it came to icons appearance, such as icons size, margin and padding, mostly for the icon's size.

is it possible to add some options relative to icons appearance?

thanks.

**Comment by Favo02** [comment]
Thank you for the feedback!

Adding customization to icons appearance makes perfect sense, but it requires a bit of work, I'll try to implement it as soon as possible.

I will keep this issue updated.

**Comment by JE-Amouel** [comment]
thanks you :pray:

**Comment by Favo02** [comment]
Added in #93, update will be released on GNOME extensions store soon.
