### ISSUE TITLE
Support for multiple monitors

### ISSUE THREAD

**Issue by Favo02** [Favo02/workspaces-by-open-apps#9]
Display in a separate workspace applications on displays with no workspaces support

**Comment by corebots** [comment]
Indeed currently the apps on a secondary screen without workspaces are being shown as if they were on each workspace. Hopefully this can be fixed!

**Comment by Favo02** [comment]
Fixed in v4 (#15)

The extension will soon be update in the gnome extension store (waiting for approval).
